extern void initializeLed(void);
extern void blinkLed1(UNS32 time_out);
extern void blinkLed2(UNS32 time_out);
extern void blinkLed3(UNS32 time_out);
extern void switchOffLed1(void);
extern void switchOnLed1(void);
extern void switchOffLed2(void);
extern void switchOnLed2(void);
extern void switchOffLed3(void);
extern void switchOnLed3(void);